<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Session\TokenMismatchException;
use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken as BaseVerifier;

class VerifyCsrfToken extends BaseVerifier
{
    /**
     * The URIs that should be excluded from CSRF verification.
     *
     * @var array
     */
    protected $except = [
        '/logout',
        '/update_preview'
    ];

    public function handle($request, Closure $next)
    {
        try {
            return parent::handle($request, $next); // TODO: Change the autogenerated stub
        } catch(TokenMismatchException $e) {
            return redirect(route('login'))->withError('error_message', 'You page session expired. Please try to login again');

        }
    }
}
