<?php

use Illuminate\Database\Seeder;

class MetadocumentsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('metadocuments')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        DB::table('metadocuments')->insert([
            [
                'id' => 1,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '1-1-CasoDeNegocio',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '1-1-CasoDeNegocio',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 2,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '1-2-NuevaPropuestaDeProyecto',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '1-2-NuevaPropuestaDeProyecto',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 3,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '1-3-EnunciadoDelAlcanceDelProyecto',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '1-3-EnunciadoDelAlcanceDelProyecto',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 4,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '1-4-EstudioDeFactibilidad',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '1-4-EstudioDeFactibilidad',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 5,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '1-5-VerificacionFaseFinalDeConcepto',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '1-5-VerificacionFaseFinalDeConcepto',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 6,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '1-6-CartaDelProyecto',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '1-6-CartaDelProyecto',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 7,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '1-7-ContratoDeTrabajoDeProyecto',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '1-7-ContratoDeTrabajoDeProyecto',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 8,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '1-8-ContratoDeConsultoria',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '1-8-ContratoDeConsultoria',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 9,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '1-9-ContratistaIndependiente',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '1-9-ContratistaIndependiente',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 10,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '1-10-ContratistaIndependienteDesarrolloDeSoftware',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '1-10-ContratistaIndependienteDesarrolloDeSoftware',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 11,
                'language_id' => 1,
                'industry_idindustry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '1-11-CotizacionDeServicios',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '1-11-CotizacionDeServicios',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 12,
                'language_id' => 1,
                'industry_idindustry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '1-12-SolicitudDePropuesta',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '1-12-SolicitudDePropuesta',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 13,
                'language_id' => 1,
                'industry_idindustry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '2-1-PlanDeGestionDelProyecto ',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '2-1-PlanDeGestionDelProyecto ',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 14,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '2-2-PlanDeGestionDeLaConfiguracion   ',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '2-2-PlanDeGestionDeLaConfiguracion   ',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 15,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '2-3-PlanDeGestionDelCronograma',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '2-3-PlanDeGestionDelCronograma',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 16,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '2-4-PlanDeGestionDelAlcance',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '2-4-PlanDeGestionDelAlcance',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 17,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '2-5-PlanDeGestionDeCalidad',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '2-5-PlanDeGestionDeCalidad',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 18,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '2-6-PlanDeControlDeCalidad',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '2-6-PlanDeControlDeCalidad',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 19,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '2-7-PlanDeGestionDeCostos',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '2-7-PlanDeGestionDeCostos',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 20,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '2-8-PlanDeGestionDeRiesgos',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '2-8-PlanDeGestionDeRiesgos',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 21,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '2-9-PlanDeGestionDeLosRequerimientos',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '2-9-PlanDeGestionDeLosRequerimientos',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 22,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '2-10-PlanDeGestionDeAdquisiciones',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '2-10-PlanDeGestionDeAdquisiciones',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 23,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '2-11-PlanDeGestionDelCambio',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '2-11-PlanDeGestionDelCambio',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 24,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '2-12-PlanDeGestionDeLasComunicaciones',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '2-12-PlanDeGestionDeLasComunicaciones',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 25,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '2-13-PlanDeEscalamientos',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '2-13-PlanDeEscalamientos',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 26,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '2-14-PlanDeGestionDeRelacionesConLosClientes',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '2-14-PlanDeGestionDeRelacionesConLosClientes',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 27,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '2-15-PlanDeGestionDeRRHH',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '2-15-PlanDeGestionDeRRHH',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 28,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '2-16-PlanDeReconocimientosYRecompensas',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '2-16-PlanDeReconocimientosYRecompensas',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 29,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '2-17-PlanDeMejoraDelProceso',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '2-17-PlanDeMejoraDelProceso',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 30,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '2-18-PlanDeDespliegue',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '2-18-PlanDeDespliegue',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 31,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '2-19-EstrategiaDeGestionDeLosInteresados',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '2-19-EstrategiaDeGestionDeLosInteresados',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 32,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '2-20-EstucturaDeDesgloseDelTrabajo',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '2-20-EstucturaDeDesgloseDelTrabajo',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 33,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '3-1-MinutaDiaria',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '3-1-MinutaDiaria',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 34,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '3-3-Retrospectiva',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '3-3-Retrospectiva',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 35,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '3-4-GuiaEntrenamientoNuevoMiembro',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '3-4-GuiaEntrenamientoNuevoMiembro',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 36,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '3-5-EvaluacionDeLasReuniones',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '3-5-EvaluacionDeLasReuniones',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 37,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '3-6-EvaluacionPeriodicaDelEmpleado',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '3-6-EvaluacionPeriodicaDelEmpleado',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 38,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '3-7-EvaluacionDesempenoProjectLeader',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '3-7-EvaluacionDesempenoProjectLeader',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 39,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '3-8-EvaluacionDesempenoDelEquipo',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '3-8-EvaluacionDesempenoDelEquipo',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 40,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '3-9-LeccionesAprendidas',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '3-9-LeccionesAprendidas',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 41,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '4-1-SolicitudDeCambio',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '4-1-SolicitudDeCambio',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 42,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '4-2-EntrenamientoDelTeam',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '4-2-EntrenamientoDelTeam',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 43,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '4-3-ExpectativasDelTeam',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '4-3-ExpectativasDelTeam',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 44,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '4-4-AnalisisDeCausaRaiz',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '4-4-AnalisisDeCausaRaiz',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 45,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '4-5-InformeDAR',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '4-5-InformeDAR',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 46,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '4-6-AceptacionDelUsuario',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '4-6-AceptacionDelUsuario',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 47,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '5-1-ChequeoDeCierreDeProyecto',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '5-1-ChequeoDeCierreDeProyecto',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 48,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '5-2-PlanDeTransicion',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '5-2-PlanDeTransicion',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 49,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '5-3-AceptacionDelProyecto',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '5-3-AceptacionDelProyecto',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 50,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '5-4-LeccionesAprendidas',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '5-4-LeccionesAprendidas',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 51,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '5-5-RevisionPostProyecto',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '5-5-RevisionPostProyecto',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 52,
                'language_id' => 1,
                'industry_id' => 1,
                'doctype_id' => 1,
                'code' => 0,
                'version' => 1,
                'name' => '5-5-RevisionPostProyecto',
                'link_logo_left' => NULL,
                'link_logo_right' => NULL,
                'path_ref' => '5-5-RevisionPostProyecto',
                'document_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            
        ]);
    }
}
